# The flow executable and arguments to use.
# JB: ABSOLUTE PATH

seed: 12345

flow_executable:
  - /home/martin/flow123d/bin/fterm
  - --no-term
  - rel
  - run
finish_sleep: 0
metacentrum: false
gmsh_executable: /home/martin/Documents/gmsh4/bin/gmsh
#gmsh_executable: /home/martin/gmsh/bin/gmsh
n_finer_level_samples: 2

mesh_window: false


# reuse existing sample directories and existing results
# None - clean dir
# False - keep dir, rerun process.py
# True - reuse existing results
#reuse_samples: true

flow_model: "flow_templ.yaml"
subscale_model: "flow_templ.yaml"


# case 1
fracture_model:
    aperture_per_size: 1e-6
    water_viscosity: 1.3e-3 #[Pa s] decrease from 1.8mPa.s at 0deg to 1.3mPa.s at 10deg,
    water_density: 1000
    gravity_accel: 9.8


levels:
  - n_samples: 4
    step: 100
    bulk_conductivity:
        choose_from_finer_level: True

  - n_samples: 4
    step: 20
    bulk_conductivity:
        # Bivariate log normal distribution for the tensor eigen values
        mean_log_conductivity: [-6, -6]
        cov_log_conductivity: [[0.2,0.07],[0.07,0.2]]
        # Von Mises for the rotation.
        # Rotation angle of the first eigen vector. Counter clockwise from the axis X.
        # dispersion == 'inf' -> uniform distribution on interval (0, 2pi)
        # dispersion == 0 -> used constant value `angle_mean`.
        angle_mean: 0
        angle_concentration: 0


# case 2
#levels:
  #- n_samples: 3
    #step: 100
    #bulk_conductivity:
        ## log10 used
        #mean_log_conductivity: [-9.97926069, -9.41656073]
        #cov_log_conductivity: [[0.0056176,  0.0022999 ], [0.0022999,  0.04078208]]
  #- n_samples: 30
    #step: 10
    #bulk_conductivity:
        ## log10 used
        #mean_log_conductivity: [-9, -9]
        #cov_log_conductivity: None

#aperture_per_size: 5e-7   # taken from WGC: initial cross_section: 5e-5m, fracture size about 100m
#water_viscosity: 8.9e-4
#water_density: 997
#gravity_accel: 9.80665
# seems that realistic fracture conductivity about 40x higher then in case 1
# however the background conductivity is also 10x higher, so we get reasonable 4x increase of the ratio




copy_files: []

#bulk_conductivity: 1e-10

#bulk_conductivity: 1e-9

# number of pressure gradient directions to apply in order to get effective tensor,  min 2
n_pressure_loads: 4



geometry:
  # square side (meters)
  fractures_box: [1000, 1000]
  domain_box: [1000, 1000]
  subdomain_box: [500, 500]
  #fractures_box: [140, 140]
  #domain_box: [140, 140]
  #fractures_box: [1000, 1000]
  #domain_box: [1000, 1000]
  #n_frac_limit: 1000

  #pow_law_size_range: [0.05, 500]
  pow_law_size_range: [ 0.1, 1000 ]
  #pow_law_size_exp: 2.8   # 3d exponent
  pow_law_size_exp: 3   # 3d exponent
  p_32: 5
  # Mean total fracture surface for the full size range (pow_law_size_range).
  # realistic value is about 0.5,
  # p_32==64 continuous for exp 3.2
  # p_32==4 almost continuous for exp 2.8
  # One of possible reasons: SKB use disc radius for the fracture size. So

  n_frac_limit: 500
  # Upper limit for the number of fractures.

  pow_law_sample_range: null #[10, 1000]
  # Actual range of fracture sizes, the mean number of samples, is determined from the p32.

  #pow_law_sample_range: [0.56, 140]
  #pow_law_sample_range: [4, 1000]

  #pow_law_sample_range: [0.56, 140]
  #pow_law_sample_range: [4, 1000]

  # 1331 fractures, exp 2.8, 2d-1d -> 65k elements;
  #fracture_mesh_step: 10

  # Uniform distribution of the fracture centers near the existing surfaces
  # in order to enhance connectivity.

  #fracture_stats:
      ## SKB data
      #-   name: NS
          #trend: 292
          #plunge: 1
          #concentration: 17.8
          #power: 2.5
          #r_min: 0.038
          #r_max: 564
          #p_32: 0.073
      #-   name: NE
          #trend: 326
          #plunge: 2
          #concentration: 14.3
          #power: 2.7
          #r_min: 0.038
          #r_max: 564
          #p_32: 0.319
      #-   name: NW
          #trend: 60
          #plunge: 6
          #concentration: 12.9
          #power: 3.1
          #r_min: 0.038
          #r_max: 564
          #p_32: 0.107
      #-   name: EW
          #trend: 15
          #plunge: 2
          #concentration: 14.0
          #power: 3.1
          #r_min: 0.038
          #r_max: 564
          #p_32: 0.088
      #-   name: HZ
          #trend: 5
          #plunge: 86
          #concentration: 15.2
          #power: 2.38
          #r_min: 0.038
          #r_max: 564
          #p_32: 0.543


  # deep data <400m
#  fracture_stats:
#      # SKB data
#      -   name: NS
#          trend: 292
#          plunge: 1
#          concentration: 17.8
#          power: 2.5
#          r_min: 0.038
#          r_max: 564
#          p_32: 0.094
#      -   name: NE
#          trend: 326
#          plunge: 2
#          concentration: 14.3
#          power: 2.7
#          r_min: 0.038
#          r_max: 564
#          p_32: 0.163
#      -   name: NW
#          trend: 60
#          plunge: 6
#          concentration: 12.9
#          power: 3.1
#          r_min: 0.038
#          r_max: 564
#          p_32: 0.098
#      -   name: EW
#          trend: 15
#          plunge: 2
#          concentration: 14.0
#          power: 3.1
#          r_min: 0.038
#          r_max: 564
#          p_32: 0.039
#      -   name: HZ
#          trend: 5
#          plunge: 86
#          concentration: 15.2
#          power: 2.38
#          r_min: 0.038
#          r_max: 564
#          p_32: 0.141



# base of the mesh file name
mesh_name: random_fractures


dfn_flow_params:
  mesh: None
