
FROM flow123d/ci-gnu:4.0.0a_d4c856
#FROM flow123d/flow123d-gnu:3.9.1

# Build-time metadata as defined at http://label-schema.org
LABEL org.label-schema.build-date="$build_date" \
      org.label-schema.name="Endorsed" \
      org.label-schema.description="Stochastic prediction of contaminant transport safety indicators for excavation damage zone." \
      org.label-schema.url="https://github.com/jbrezmorf/Endorse" \
      org.label-schema.vcs-ref="$git_hash" \
      org.label-schema.vcs-url="https://github.com/jbrezmorf/Endorse" \
      org.label-schema.vendor="Technical University of Liberec" \
      org.label-schema.version="0.0.1"



RUN sudo apt-get update
RUN sudo apt install -y curl libglu1-mesa redis git
RUN git clone --recurse-submodules -j4 https://github.com/jbrezmorf/Endorse.git /opt/endorse
RUN cd /opt/endorse && sudo python3 -m pip install -r requirements.txt
RUN cd /opt/endorse && sudo python3 -m pip install .
